services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  graphql:
    build: ./graphql-server
    container_name: graphql-server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/?authSource=admin

  ingest:
    build: ./ingest
    container_name: data_ingest
    depends_on:
      - mongo
    restart: always
  ia:
    build: ./ia
    container_name: ia
    ports:
      - "5000:5000"
    volumes:
      - ./ia:/app
    depends_on:
      - mongo
    restart: always
volumes:
  mongo_data:
